"use Client";
import { AppWrapper  } from "@/contextApi";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>

        <AppWrapper>
          {children}
        </AppWrapper> 

      </body>
    </html>
  )
}
